# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appCentre' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appCentre
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  target 'appCentreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'appCentre-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appCentre-tvOS

  target 'appCentre-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
